### ISSUE TITLE
Some problems with parameter (multiple) dependencys

### ISSUE THREAD

**Issue by Adminius** [KONNEKTING/KonnektingSuite#39] opened 2017-04-18 19:06 UTC
For test:
https://github.com/KONNEKTING/KonnektingFirmware/blob/master/Multi-Interface/IR_Transmitter_1.0/IR_Transmitter.kdevice.xml

1: Go to group "Script 1"-> OK (all params except "IR Code 1" are invisible)
2: Script 1: change IR Code 1 from "Script inactive" to something else
3: Script 1: change IR Code 2(-5) from "unused" to something else
4: Script 1: change IR Code 1 to "Script inaktiv" -> we should see only "IR Code 1"

IR Code 2-5 + Delays has more then one dependency, but only one "wins".

**Comment by tuxedo0801** [comment] 2017-04-19 05:52
Have you found a workaround?

**Comment by tuxedo0801** [comment] 2017-04-19 06:22
Downloaded the XML, but was not able to understand what you're trying to do ...

Please be more precise what you change where. 
Example:

>  change IR Code 1 from "Script inactive" to something else

This is not possible at all. There's a param group "IR Code 1", but there's just a Option-Parameter called "type", which is by default "Unused". 
Seems you're mixing up "IR Code 1":"Type" with "Script 1":"IR Code 1" ...

I'm more than confused...

Beside that: If I remember right, you can't have multiple dependencies for a single parameter. The system does not know if multiple dependencies have to be ANDed or ORed. It's a very simple dependency logic. So the first one wins. BUt I'll check the code to have more clarity.

Though, I would recommend to re-phrase your test-case...

**Comment by tuxedo0801** [comment] 2017-04-19 06:26
I was right:

https://github.com/KONNEKTING/KonnektingDeviceConfig/blob/master/src/main/java/de/konnekting/deviceconfig/DeviceConfigContainer.java#L773

The first parameter-dependency thsat matches the questioned parameter is used to decide about the visibility of the dependency. Any further dependencies for this parameter are ignored.

**Comment by Adminius** [comment] 2017-04-19 07:09
i mean a group "Script 1" and not "IR Code xx"-groups.

If IR Code 1 = "Script inactiv" => all paramters should be invisible, because this script is inactiv. But All paramters has dependency under each other.

I this case i need multi dependencys.

**Comment by tuxedo0801** [comment] 2017-04-20 06:55
Duplicate of #30 
--> Closed.

**Closed by tuxedo0801** 2017-04-20 06:55 UTC
Labels: bug
